title: Digitalt Design og Udvikling
description: Slotshaven Gymnasium
theme: jekyll-theme-cayman

collections:
  test:
    output: true
  
defaults:
  - scope:
      path: ""
      type: test  # Name of the collection
    values:
      theme: default