title: Digitalt Design og Udvikling
description: Slotshaven Gymnasium
theme: jekyll-theme-cayman

collections:
  test:
    output: true
  minikurser:
    output: true
    permalink: /minikurser/:name/
  forloeb:
    output: true
    permalink: /forloeb/:name/
defaults:
  - scope:
      path: "sider"
    values:
      permalink: /:slug/ # Default permalink for pages in the sider directory
  - scope:
      path: ""
      type: forloeb  # Name of the collection
    values:
      published: true
      layout: default
  - scope:
      path: ""
      type: minikurser  # Name of the collection
    values:
      published: true
      layout: default
  - scope:
      path: ""
      type: test  # Name of the collection
    values:
      published: true
      layout: default # Change this if you want a different layout for the test collection