title: Digitalt Design og Udvikling
description: Slotshaven Gymnasium
theme: jekyll-theme-cayman

collections:
  test:
    output: true
  minikurser:
    output: true
    layout: default
  forloeb:
    output: true
    layout: default
defaults:
  - scope:
      path: ""
      type: forloeb  # Name of the collection
    values:
      published: true
  - scope:
      path: ""
      type: minikurser  # Name of the collection
    values:
      published: true
  - scope:
      path: ""
      type: test  # Name of the collection
    values:
      published: true
      layout: default # Change this if you want a different layout for the test collection